### ISSUE TITLE
Document current release process

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/community#105]
Create a document that contains information about the release process. 
The input from @crabtree:

1. Create release branch in kyma repository - only done when creating new release, not bugfix release
        a. Name of this branch should follow pattern release-x.y (example release-0.4)
2. Bump versions and dirs parameters in values.yaml files in root charts, setting those to desired version which will be released. Commit and push this file to release branch
3. Run release pipeline on Jenkins (before you can run this pipeline all components and governance plan need to be changed. The merging strategy needs to be disabled for time of running release pipeline)
4. Run pipeline for releasing kyma-installer from release branch and set version to release version
5. Produce local and cluster combo yamls
        a. ./installation/scripts/generate-kyma-installer.sh ./installation/resources/installer-config-local.yaml.tpl > kyma-config-local.yaml
        b. ./installation/scripts/generate-kyma-installer.sh ./installation/resources/installer-config-cluster.yaml.tpl > kyma-config-cluster.yaml
6. In generated combo yamls set apropriate kyma-installer image (produced in step 4)
7. Attach artifacts and readme to release on github

**Comment by derberg** [comment]
this should be done once prow is in place cause now that would be complicated docs that would try to be generic because we have some internal docs for now because we still depend on jenkins

**Comment by pbochynski** [comment]
Done with prow migration: https://github.com/kyma-project/test-infra/blob/master/docs/prow/release-process.md
