### ISSUE TITLE
Service Catelog document link is broken

### ISSUE THREAD

**Issue by i042416** [kyma-project/community#129]
**Description**

When I go to page: https://kyma-project.io/docs/components/serverless#

scroll down to the bottom and click the service catalog hyperlink:

![image](https://user-images.githubusercontent.com/5669954/48667895-eb5a2d00-eb1b-11e8-8375-bb47caeff3d1.png)

it does not work:

![image](https://user-images.githubusercontent.com/5669954/48667904-09279200-eb1c-11e8-914e-325c2d95717d.png)

**Expected result**

The document page for service catalog is displayed.

**Actual result**

**Comment by kazydek** [comment]
Related PR: https://github.com/kyma-project/kyma/pull/1728/

**Comment by kazydek** [comment]
The link was removed and doc image was updated.
