### ISSUE TITLE
Improve the table with the templates

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/community#132]
The table with the templates may be a bit unclear when it comes to the README.md documents. Improve the table so that it makes it clear when to use a given README template.

**Comment by kazydek** [comment]
Basically, it is about changing the description of this template to mention it should not only be used for the main README.md in the project but for the subdirectories as well:
![templates](https://user-images.githubusercontent.com/40655785/49643524-3b8b2780-fa16-11e8-99d5-0ff8b98d9ec8.png)
