### ISSUE TITLE
Proposal - Run kyma-eventing on top of knative-eventing

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/community#166]
|Created on| Created by|
|-|-|
|2018-12-17|Marco Bebway (@marcobebway)|

**Purpose**

Having the option to run **kyma-eventing** on top of **knative-eventing**.

**Use-cases**

1. Kyma runs by default with the **event-bus** and **nats-streaming** messaging system.
2. Kyma runs on top of **knative** and **knative-eventing** when the **knative** flag is provided to the kyma installer.

**Design**

Kyma is installed on top of Knative and using knative-eventing abstraction to publish and deliver messages:
- The Publisher sends messages to the Publish app. Each message should contain the event-type and source-id.
- The Kyma Publish app receives the publish request from the publisher and sends the message to the corresponding knative channel related to the event-type provided with the publish request.
- The Knative Dispatcher stores messages to the underlying messaging system backend.
- The Kyma SubscriptionController app acts upon events coming from Kubernetes for the Kyma subscription-crd and the Kyma event-activation-crd, and it creates a knative-subscription for a specific Knative channel.
- The Knative Provisioner Controller manages subscriptions on the underlying messaging system backend.
- The Knative Provisioner Dispatcher delivers messages to the subscriber endpoint.

![design](https://user-images.githubusercontent.com/24314423/50688731-1e527480-1027-11e9-8fe2-adf500bdccf5.png)

 - Kyma EventBus sends messages to multiple Knative channels each of which can be tied to different Knative Provisioner.

![design-pluggability](https://user-images.githubusercontent.com/24314423/50688738-26aaaf80-1027-11e9-87e4-871472492764.png)

**Development**

- Create two new apps inside the **event-bus** component codebase, one for the **publish-knative** app and the other for **subscription-controller-knative** app.

  > Note: The **publish-knative** app should expose a publish API to publish messages from kyma to knative-eventing. The publish API should expect two required parameters the **event-type** and the **source-id**.

  > Note: The **subscription-controller-knative** app should act upon the events coming from Kubernetes regarding the Kyma **subscription-crd** and the Kyma **event-activation-crd**, and it should create a corresponding Knative **subscription**. In addition, it should send requests to the Knative provisioner controller to store the subscriptions in the underlying messaging system backend.

  > Note: We need to come up with a convention to map kyma-subscription(s) to knative-subscription(s).

**Deployment**

- Move **event-bus** helm chart from **kyma/resources/core/charts/event-bus/** to **kyma/resources/event-bus**.

- Create a new helm chart for **event-bus-knative** component inside **kyma/resources/event-bus-knative**.

- Move **nats-streaming** helm chart from **kyma/resources/core/charts/event-bus/charts/nats-streaming** to **kyma/resources/nats-streaming**. As a constraint by Knative, the **nats-streaming** messaging system should **not** be installed in the **knative-eventing** namespace. Also it should be installed in a namespace which is **istio-injection** enabled. In general, it can be installed in the **kyma-system** namespace which is **istio-injection** enabled.

- Create a new helm chart for **nats-streaming-provisioner** under **kyma/resources/nats-streaming-provisioner**. As a constraint by Knative, the **nats-streaming-provisioner** **must** be installed in the **knative-eventing** namespace. Also it should have a dependency entry in the **kyma/resources/core/charts/event-bus-eventing/requirements.yaml** to install it when Kyma runs on top of Knative.

  The new directory structure should look like this:
  ```
  .
  ├── kyma/
  │   └── resources/
  │       ├── .
  │       ├── event-bus/
  │       ├── event-bus-knative/
  │       ├── nats-streaming/
  │       ├── nats-streaming-provisioner/
  │       ├── .
  ```

- Update the template files **kyma/installation/resources/installer-cr.yaml.tpl** and **kyma/installation/resources/installer-cr-cluster.yaml.tpl** to include the components **nats-streaming** and **event-bus** under the **spec/components**.

- Update the template files **kyma/installation/resources/installer-cr-knative.yaml.tpl** and **kyma/installation/resources/installer-cr-cluster-knative.yaml.tpl** to include the components **nats-streaming**, **nats-streaming-provisioner** and **event-bus-knative** under the **spec/components**.

- Update the knative charts inside **kyma/resources/knative/** to use the proper knative version that has the **nats-streaming-provisioner** supported.

**Design decisions**

- There are two separate helm charts for **event-bus** and **event-bus-knative**, because both are serving two different purposes.
- There is one **nats-streaming** helm chart which is used for both **event-bus** and **event-bus-knative**, because the deployment of the **nats-streaming** messaging system remain the same for the two use-cases. The only constraint in case of Kyma is running on top of Knative, is **not** to install **nats-streaming** in the **knative-eventing** namespace. Also it has to be installed in a namespace that is **istio-injection** enabled.
- There is a separate chart for **nats-streaming-provisioner**, because it will be installed only in case of Kyma running on top of Knative.
- There are two new apps **publish-knative** and **subscription-controller-knative** introduced inside the **event-bus** component codebase for clear separation of concerns and responsibilities.

**Installation**

- Run Kyma installer and provide the **knative** flag to install **knative**, **knative-eventing** and **nats-streaming-provisioner**.
- Installing multiple Provisioners on a running kyma cluster should be applicable using helm charts by putting the provisioners under the **kyma/resources/** directory.

**Comment by abbi-gaurav** [comment]
```
The nats-streaming helm chart should use the global.knative flag to apply the proper configuration for the nats-streaming messaging system. If the flag is set to true, then the knative nats-provisioner configuration should be applied, otherwise the default kyma nats-streaming configuration should be applied.
```

Not clear if the provisioner is a part of NATS Streaming or a separate chart.

**Comment by abbi-gaurav** [comment]
We should also mention how the provisioners (OOB based on NATS Streaming) and XYZ will be installed.
Will the NATS based provisioner be a separate helm chart?
In which namespaces various pieces will be installed?

Any assumptions made that needs to be verified?

**Comment by radufa** [comment]
- NATS Streaming should be installed, if it's possible, using the same chart on both environments (with and without KN). The only constraint on KN installation is that it should be NOT installed in the knative-eventing namespace and the namespace where it's installed should be "istio" enabled. 
So that we can let NATSS to be installed like today in "kyma-system"...
- NATSS provisioner must be installed in "knative-eventing" namespace. This is today a must for all additional provisioners, inclusive the new XYZ.

**Comment by marcobebway** [comment]
@abbi-gaurav @radufa I updated the proposal based on your comments. Please have a look.

**Comment by abbi-gaurav** [comment]
Please consider adding the rationale behind using one chart to install nast streaming and optionally nats streaming provisioner based on knative flag.

Since they will go in two different namespaces (kyma-system and knative-eventing), please provide details how this should be handled?

**Comment by abbi-gaurav** [comment]
LGTM

**Comment by lilitgh** [comment]
waiting for wg-knative feedback. Deadline is 10th of Jan

**Comment by davy-hybris** [comment]
Some of the language is a little confusing in here.  In my understanding, in Knative, events are only sent to channels, not to provisioners. The provisioners are responsible for deploying or configuring the necessary pieces for a specific channel implementation.  Several places above, the proposal states that events are sent to specific provisioners.  My concern here would be that the Kyma implementation does not become tied to some specific assumptions about how different channel types are implemented in KNative.

Also, could you explain the role of the 'Publisher' relative to KNative event sources?  All of the implemented KNative event sources are agnostic as to which channel implementation is being used.  In contrast, the proposal above states that the 'Publisher' should specify the chanel type to use.  This choice would seem to limit interoperability of other KNative event sources with Kyma.

**Comment by marcobebway** [comment]
@davy-hybris thanks for your feedback.

I updated the proposal according to your comments.
