### ISSUE TITLE
Governance job does not send notifications about broken links in the `community` repo

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/community#245]
**Description**

The periodic governance job does not show notifications about broken links in the `community` repo, which makes it difficult for the TWs to monitor and fix dead links. 

**AC:**

- Fix governance job so that it shows dead links in the `community` repo

**Comment by tehcyx** [comment]
I've talked to @magicmatatjahu and he'll investigate on the tool used, if the problem still persists or is already fixed.
From the viewpoint of the job definition, there is no improvement possible.

**Comment by tehcyx** [comment]
Moving this to Wookie backlog.

**Comment by michal-hudy** [comment]
@klaudiagrz is this still valid?

**Comment by michal-hudy** [comment]
I'm closing this issue as there was no response from the author. Please reopen if the problem is still valid.
