### ISSUE TITLE
Describe the release process communication in the `release-process.md`

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/community#265]
**Description**

Update the `release-process.md` and add a step regarding internal and external communication regarding the RC1, RC2, and final release dates. Mention which Slack channels should be used to communicate the progress of the release process (xf-team, scrum-masters, sig-community?). Mention also the SoS and SoS MagicBox. 

**Reasons**

Make the release process more clear and transparent to everyone.

**Comment by derberg** [comment]
What is SOS and SOS MagicBox for the community? even I have no idea what is magicbox :D

**Comment by klaudiagrz** [comment]
@derberg This PR is an AI from the previous Kyma Retrospective during which it was agreed to create a doc/section that mentions all the channels used to communicate the release progress. One of such a communication way is scrum masters Scrum of Scrums (SoS) meeting. A release manager should cooperate with a scrum master regarding updates of the release progress which are later presented during SoS meetings. This should all be described in this PR. 

Naturally, all the release-related docs should be grouped in [one directory](https://github.com/kyma-project/community/tree/master/guidelines/releases) so that a release manager has everything written down in one place.
