### ISSUE TITLE
Update pull request and issue templates

### ISSUE THREAD

**Issue by derberg** [kyma-project/community#28]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

Since there were changes in the PR template introduced by this PR: [https://github.com/kyma-project/community/pull/12,] TWs need to adjust other templates to those changes.

1) Copy the pull request template (https://github.com/kyma-project/community/blob/master/.github/pull-request-template.md) to the repository template here: https://github.com/kyma-project/community/blob/master/guidelines/internal-guidelines/repository-template/template/.github/pull-request-template.md and in all repositories, other than the `community` repository, under `/.github/pull-request-template.md` location.
2) You need to get rid of checkboxes from all issue templates now and basically remove that phrase with hidden descriptive points (use PR template as a reference):
```
Confirm these statements before you submit the issue:

- [ ] I have searched open and closed issues for duplicates.
- [ ] I have read the contributing guidelines.
---

```

The replacement of the checkboxes with hidden descriptions needs to be done on all repos and in the repository-template that is in the community repo. There are three issue templates on each repo:
1. General issue template under `/.github/issue-template.md`
2. Bug report template under `/.github/ISSUE_TEMPLATE/bug-report.md`
3. New feature template under `/.github/ISSUE_TEMPLATE/feature-request.md`

**Comment by derberg** [comment]
Just small comment from my side, this `Description` heading doesn't bring much value to the PR details as the whole part of the PR details is a description ;)
When I do PR I always remove it, others also use is strange

`**Related issue(s)**` doesn't need to be bolded too

**Comment by kazydek** [comment]
As discussed, to keep the consistency with other templates, I will keep the Description heading and bolding.

**Comment by kazydek** [comment]
Done. @derberg, pls take a look at PRs:
https://github.com/kyma-project/website/pull/30
https://github.com/kyma-project/luigi/pull/32
https://github.com/kyma-project/console/pull/81
https://github.com/kyma-project/examples/pull/26
https://github.com/kyma-project/kyma/pull/452
https://github.com/kyma-project/community/pull/45

**Comment by kazydek** [comment]
Merged the PRs.
