### ISSUE TITLE
Update issues-workflow.md re: lables 

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/community#307]
**Description**

The [issues-workflow.md](https://github.com/kyma-project/community/blob/master/issues-workflow.md) file in the community repo is not up-to-date. 
- The custom labels descriptions are missing colors that should be used for particular labels. 
- The diagram under Issues Triage section includes labels with incorrect colors.

See the correct labels' colors [here](https://github.com/kyma-project/kyma/labels)

**Reasons**

Updated documentation.

**Comment by valentinvieriu** [comment]
Can we try not to hardcode the labels on the webpage, and just link to the source, so if that changes, we don't have to keep the page updated?

**Comment by valentinvieriu** [comment]
This is stale for some time. We will close it
