### ISSUE TITLE
Prepare a template for Overview document

### ISSUE THREAD

**Issue by derberg** [kyma-project/community#31]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- Prepare a template and store in one location with other documentation templates in guidelines directory
- Base the template on already existing documents
- Be consistent with already existing templates: https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/cli-reference.md or suggest refactor that will have to be done also in other templates

As a follow-up task, adjust the existing **Overview** documents to the template.

**Reasons**

Every documentation topic must follow https://github.com/kyma-project/community/blob/master/guidelines/content-guidelines/content-strategy.md#documentation-types and all those types must have templates which make it much easier for anybody to contribute content

**Comment by kazydek** [comment]
A follow-up task: https://github.com/kyma-project/kyma/pull/550/files
