### ISSUE TITLE
Update choice columns in tables

### ISSUE THREAD

**Issue by kazydek** [kyma-project/community#310]
**Description**

- Add info to the content guidelines to:
   - Use **Yes / No** in the choice columns in tables.  
   - Use **Required** as the name of the choice columns.  
- Update existing documents in the `kyma` repository accordingly.

**Comment by mmitoraj** [comment]
The [guidelines](https://github.com/kyma-project/community/blob/master/guidelines/content-guidelines/04-formatting.md#tables) in the `community` repo are already updated.
