### ISSUE TITLE
Add Custom Resource documentation for SBU, UK, EM, EA, RE

### ISSUE THREAD

**Issue by derberg** [kyma-project/community#32]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- Document ServiceBindingUsage, UsageKind, EnvironmentMapping, EventActivation, RemoteEnvironment
- Use this template https://github.com/kyma-project/community/issues/25

**Reasons**

be consistent across all documentation topic and document Custom Resources the same way everywhere

**Comment by PK85** [comment]
1SP for dev
