### ISSUE TITLE
Update templates for release notes with info on fixed security vulnerabilities

### ISSUE THREAD

**Issue by kazydek** [kyma-project/community#328]
**Description**

To meet [CII Best Practices](https://bestpractices.coreinfrastructure.org/en/projects/2168) requirements, we must have a section on fixed security vulnerabilities in release notes.

That requires an update of the existing release notes templates (for Technical Writers and the Product Owners that provide RN input).

The **Fixed security vulnerabilities** section should include this info:
- Vulnerability's short description
- Calculated risk assessment 
- Link to a PR which fixes the related issue (and link to the issue, if available)

>**NOTE:** The risk assessment codes are available in the [Security Vulnerability template](https://github.com/kyma-project/community/issues/new?template=security-vulnerability.md) on every repository.

Update these docs:
- [RN template](https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/release-notes.md) for Technical Writers
- [Input template](https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/release-notes-input.md) for Product Owners

**Comment by mmitoraj** [comment]
[Input template](https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/release-notes-input.md) for Product Owners already updated.
