### ISSUE TITLE
Formatting bugs in the release-process.md + refactoring

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/community#347]
**Description**

The [**Release process**](https://github.com/kyma-project/community/blob/master/guidelines/releases-guidelines/02-release-process.md)  document requires refactoring as with time it has become not user-friendly. The release process flow is more and more complex and involves actions in many repositories. The guidelines should be as simple as possible to help go through the release process. 

Suggestions:
- move the content of **kyma-project/cli** to a separate document
- move the content of **Release process improvement** to a separate document
- try to limit the number of steps 

Fix formatting bugs in the release-process.md:

- incorrectly formatted code block

![2019-08-12_15-02-34](https://user-images.githubusercontent.com/23300533/62866876-3f441c00-bd12-11e9-83cb-3be7ca10353d.png)

- pictures don't render

![2019-08-12_15-03-30](https://user-images.githubusercontent.com/23300533/62866952-6ac70680-bd12-11e9-9f75-3e699630ee52.png)

**Expected result**

User-friendly release process guidelines with fixed formatting.

**Comment by nachtmaar** [comment]
Most of the problems should be solves by https://github.com/kyma-project/community/pull/334
