### ISSUE TITLE
Update the Task Force Operations Manual

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/community#391]
**Description**

Update the diagram in the **How-to Procedures** section of the [Task Force Operations Manual](https://wiki.hybris.com/display/ysf/Task+Force+Operations+Manual) according to the [Flaky tests proposal](https://github.com/kyma-project/community/issues/369).

**Reasons**

Consistent processes in Kyma.

**Comment by aerfio** [comment]
Already taken care of.
