### ISSUE TITLE
Update documentation about release process

### ISSUE THREAD

**Issue by aszecowka** [kyma-project/community#400]
1. In documentation there is missing information about a cherry-picking procedure.
For Release Master it should be no-brainer. My proposal is to cherry-pick only blockers. Blocker definition needs to be provided.

2. Communication about PR images used in master branch should occur earlier, than in the day of creating RC1. 
Release Master can easily execute script locally that checks PR images and should communicate it on Friday before release.

3.
> CAUTION: The cluster is automatically generated for you, so you don't need to create it. The release cluster, the IP Addresses, and the DNS records must be deleted manually after tests on the RC2 cluster are done.

Why RC2 is mentioned here?

4.
> Follow these instructions to give Kyma teams access to start testing the release candidate.

This link does not work.

5. The section about communication with Breaking Pixels is outdated: team is renamed to Fixing Pixels, and we should communicate through #kyma-cockpit-integration.

6. 
>  These issues are tagged with the quality/release label and added to the Release Improvement Backlog.

Such label does not exist anymore

**Comment by Disper** [comment]
Point 1) @jose-cortina could you define that? It would be required to have that before implementation of this improvement can start.

Point 3) Additional point in the release procedure should be added so the release master manually checks usage of PR images. It could be done e.g. one day before release branch is created. 
@jose-cortina could you confirm that as well?

Point 5) @jose-cortina & @derberg what are your thoughts on that? Would it be fine to change it to use #kyma-cockpit-integration channel as only people in the organization are doing release? Or should we maybe move this channel to the public slack and bring Fixing Pixels there? 

Point 6) It's ok to use label 'area/quality'

**Comment by derberg** [comment]
`#kyma-cockpit-integration` is internal thingy that means nothing to community, should not be in public docs

**Comment by jose-cortina** [comment]
> Point 1) @jose-cortina could you define that? It would be required to have that before implementation of this improvement can start.

See #404 

> Point 2) Additional point in the release procedure should be added so the release master manually checks usage of PR images. It could be done e.g. one day before release branch is created.

Instead of trying to make releases quicker, we seem to be adding more time to the process. Is there an alternative that would not increase the number of days we need to release?

> Point 3) Why RC2 is mentioned here?

I understand the original text as information that RC clusters should be cleaned up, and this applies to any test cluster created for the release, and not specific to RC2.

> Point 5) @jose-cortina & @derberg what are your thoughts on that? Would it be fine to change it to use #kyma-cockpit-integration channel as only people in the organization are doing release? Or should we maybe move this channel to the public slack and bring Fixing Pixels there?

Not sure if we should have this here at all, as this is an internal process.
