### ISSUE TITLE
Add security contact details to the website

### ISSUE THREAD

**Issue by kazydek** [kyma-project/community#417]
It was pointed out that there are no security contact details (no email `security@googlegroups.com`) on the `https://kyma-project.io/` website. Although we have this info in the `community` repository [here](https://github.com/kyma-project/community#security), it is not exposed anywhere.

This email should be placed somewhere on the main community page -> https://kyma-project.io/community/get-started/.  Also, check if that is enough or maybe we also need to add info on the security issue template?

For more info, contact @natasab who reported this requirement.

**Comment by natasab** [comment]
Please unstale :)

**Comment by natasab** [comment]
Please unstale
