### ISSUE TITLE
Request for maintainer role

### ISSUE THREAD

**Issue by ksputo** [kyma-project/community#418]
**Description**
I would like to grant a codeowner role in **Service Management** area: [pull request](https://github.com/kyma-project/kyma/pull/6364)

**List of contributions**
- [kyma-project/kyma](https://github.com/kyma-project/kyma/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aksputo+is%3Aclosed+is%3Aopened)
- [kyma-project/helm-broker](https://github.com/kyma-project/helm-broker/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Aclosed+is%3Apr+author%3Aksputo+)
- [kyma-project/test-infra](https://github.com/kyma-project/test-infra/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aksputo+is%3Aclosed+is%3Aopened)

- [kyma-incubator/github-slack-connectors](https://github.com/kyma-incubator/github-slack-connectors/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aksputo+is%3Aclosed+is%3Aopened)

**Comment by polskikiel** [comment]
@ksputo fulfills all the requirements to be a member of our organization. I approve this request.

**Comment by a-thaler** [comment]
Looks good after talking to Kamil, approved. Will discuss in next steering committee call how to process such tickets in future.
