### ISSUE TITLE
New incubator repository for fluentbit

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/community#421]
Description

I would like to as for permission to create a new repository in kyma-incubator org: fluentbit

Reasons
To open up our logging system we like to use fluentbit as log forwarder instead of promtail as it is more widely-adopted and supports multiple target outputs. To get rid of promtail fully, we need to customize the fluentbit image and ad there a library provided by Loki. Furthermore a distroless base image should be used.

**Comment by ormos** [comment]
approved

**Comment by pbochynski** [comment]
approved

**Comment by a-thaler** [comment]
Repository located here: https://github.com/kyma-incubator/fluentbit
