### ISSUE TITLE
kyma-incubator: new repository request

### ISSUE THREAD

**Issue by jakkab** [kyma-project/community#427]
**Description**

I would like to ask for permission to create a new repository in kyma-incubator org: namespace-rbac-controller.

**Reasons**

Goat team are working on a k8s controller:
https://github.com/kyma-project/kyma/issues/6784

**Comment by jakkab** [comment]
@piotrmsc suggested that "namespace-permission-controller" would be a better name.

**Comment by piotrmsc** [comment]
Or permissions-controller

**Comment by pbochynski** [comment]
The convention is to extract only bigger modules responsible for the entire area, therefore I would suggest to keep that controller inside kyma repository. Please create just a new component in kyma-project/kyma.
