### ISSUE TITLE
Request for codeowner role for @rafalpotempa

### ISSUE THREAD

**Issue by rafalpotempa** [kyma-project/community#441]
**Description**

I would like to be granted a codeowner role in **Application Connectivity** and **Compass** areas.

Pull requests:
- https://github.com/kyma-project/kyma/pull/7613
- https://github.com/kyma-incubator/compass/pull/974

**Contributions**
- Kyma
  - https://github.com/kyma-project/kyma/pull/6042
  - https://github.com/kyma-project/kyma/pull/6085
  - https://github.com/kyma-project/kyma/pull/6463
  - https://github.com/kyma-project/kyma/pull/7138
- Test Infra
  - https://github.com/kyma-project/test-infra/pull/1567
  - https://github.com/kyma-project/test-infra/pull/1633
  - https://github.com/kyma-project/test-infra/pull/1672
  - https://github.com/kyma-project/test-infra/pull/1912
  - https://github.com/kyma-project/test-infra/pull/1986
  - https://github.com/kyma-project/test-infra/pull/2006
- Compass
  - https://github.com/kyma-incubator/compass/pull/432
  - https://github.com/kyma-incubator/compass/pull/613
  - https://github.com/kyma-incubator/compass/pull/666
  - https://github.com/kyma-incubator/compass/pull/887
- Github-Slack Connector
  https://github.com/kyma-incubator/github-slack-connectors

**Comment by a-thaler** [comment]
Looks good to me

**Comment by pbochynski** [comment]
LGTM

**Comment by a-thaler** [comment]
Welcome to the team :)
