### ISSUE TITLE
Define template for security issues

### ISSUE THREAD

**Issue by derberg** [kyma-project/community#46]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- template should contain
  - information about the security email address, that user can use it if he doesn't want to make his security finding public
  - explanation what labels to use for security issues (`security/{score}`)
- publish template in all repositories like in case of other templates

**Reasons**

- have clear specification of how to define a good security issue and remind user that he can keep those secret
- show that we treat security seriously

**Comment by derberg** [comment]
@meeque please provide more details whenever you have time

**Comment by meeque** [comment]
Regarding the labels:
It seems that non-collaborators cannot label issues. Can anyone confirm?
If so I'd still document how we use labels, but state that external reporters don't need to care about it...

**Comment by derberg** [comment]
@meeque you mean something more than https://github.com/kyma-project/community/blob/master/issues-workflow.md ?

**Comment by meeque** [comment]
@derberg Should we reference that in this template though? Seems a little much?

**Comment by derberg** [comment]
Issue defined and merged
Issue template propagated to all the other repositories
