### ISSUE TITLE
Link docs to docs/latest

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/community#462]
**Description**

At this moment we have docs/latest in the sitemap.xml and in the navigation url we point to /docs that is ignored by the robots.txt

**Expected result**

We should be consistent and use /docs/latest or remove the robots.txt ignore

**Actual result**

we are linking to a page that is ignored in robots.txt ( /docs/ )

**Comment by kazydek** [comment]
If we decide to go for `/docs/latest` we would also need to update all links in docs.

**Comment by valentinvieriu** [comment]
I've realised that I've created the issue in the wrong repo.
https://github.com/kyma-project/website/issues/580
