### ISSUE TITLE
Consolidate all the Kyma domain names 

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/community#467]
At this moment the kyma domains are spread out to various members of the community. 
We should consolidate all under one registrar controlled by the Kyma project

Known Kyma domains:

- [Kyma-project.io](https://Kyma-project.io)
- [kyma.dev](http://kyma.dev)

**Comment by valentinvieriu** [comment]
I propose to consolidate all domains under [NameCheap](https://www.namecheap.com/) and then use [CloudFlare](https://cloudflare.com) as a DNS provider and also Caching when needed

**Comment by evilyeti** [comment]
We have a bunch of additional domains in the picture, all of which are currently redirecting to kyma-project.io:
- [kyma-project.dev](https://kyma-project.dev) 
- [kyma-project.org](https://kyma-project.org)
- [project-kyma.io](https://project-kyma.io) - deception avoidance
- [kyma.academy](https://kyma.academy) - potentially consolidate here all tutorials, courses, etc. 
- [kyma.app](https://kyma.app) - potential domain for hosted kyma apps. 
- [kyma.dev](https://kyma.dev) - grabbed that once the DEV registrar went live. Looks better if we want to cater to developers. 
- [kyma.services](https://kyma.services) - potential target to build a services ecosystem/catalog of systems consumable from Kyma
- [kyma.cloud](http://kyma.cloud)

We also have [refter.dev](https://rafter.dev) which I'm not sure whether we want to renew going forward - it's our call to make until November :).

**Comment by k15r** [comment]
Just to keep everything domain related in one place:
how about introducing a vanity importpath (https://golang.org/cmd/go/#hdr-Remote_import_paths)  for kyma so that we could `import kyma-project.io/<yourpackagegoeshere>`

**Comment by valentinvieriu** [comment]
@k15r can you move that request in a separate issue, maybe in the kyma repo?
This topic was related to all the domain names that we have under the Kyma projects, and consolidate them under one common account

**Comment by valentinvieriu** [comment]
@evilyeti we have 1 more domain left kyma-project.io
