### ISSUE TITLE
New kyma repository for control-plane

### ISSUE THREAD

**Issue by dbadura** [kyma-project/community#479]
Description
I would like to ask for permission to create a new repository in kyma-project org: `control-plane`.

**Reasons**
We would like to move `kyma-environment-broker`, `metris`, `kubeconfig service` and `provisioner` components from `compass` to a separate repository.

**Comment by ormos** [comment]
Approved from my side. Please double-check with @pbochynski

**Comment by dbadura** [comment]
The repo is created. Closing the issue.
