### ISSUE TITLE
Drop the definite article from the components' names

### ISSUE THREAD

**Issue by majakurcius** [kyma-project/community#481]
**Description**

Drop the definite article `the` from the components' names. 
Example: `Application Connector`, not ~~`the Application Connector`~~.
The Kyma repositories affected are mainly: 
- [Kyma](https://github.com/kyma-project/kyma)
- [Control Plane](https://github.com/kyma-project/contorl-plane)

**Reasons**

So far we've been using the definite article `the` in front of our components' names. However, this sometimes resulted in longer and cumbersome sentences. We felt that dropping it would simplify our documentation, improve its readability and make the names sleeker. 
That is why it was agreed with the Technical Writers to drop the `the` and go with the bare names of the components. 

**AC**

- [x] guidelines added
- [x] documentation updated

**Comment by NHingerl** [comment]
I added this to [PR 693](https://github.com/kyma-project/community/pull/693/files).
