### ISSUE TITLE
New kyma repository for function-cli

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/community#505]
**Description**
I would like to ask for permission to create a new repository in kyma-incubator org: `function-cli`.

**Reasons**
We would like to write the whole code for [this task](https://github.com/kyma-project/cli/issues/551) in a separate repository.

**Comment by rakesh-garimella** [comment]
@pPrecel  I would recommend to add the code here https://github.com/kyma-incubator/hydroform as we already have a repo that can be used to create SDK for kyma. Currently its being used to for provisioning the cluster and installing kyma. This can be extended to have the implementation for functions and in future for other components. Please ask me or @clebs or @suleymanakbas91  if you need further assistance.

**Comment by pbochynski** [comment]
Why it should be a separate repository? I would rather add a new package to kyma CLI. The only reason I see is [Conway's Law](https://en.wikipedia.org/wiki/Conway%27s_law)

**Comment by pPrecel** [comment]
Thanks @rakesh-garimella. Now we're after syncing with @clebs. We will contribute to the `hydroform`
