### ISSUE TITLE
Proposal "Kyma Showcase Application" WG creation

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/community#509]
**Proposal type**

* Working Group (WG)

**Name**
* Full name of the group: Kyma Showcase Application

* Abbreviated name: showcase-app

**Earliest start date**

* 2020-10-01

**Visibility**
* Public

**Keywords** (optional)

* demo
* showcase
* getting-started

**Proposers**

* @valentinvieriu  

**Purpose and goals**

Build a Unified Demo Project with a consistent story to showcase a the complete functionality and features of Kyma. This application should be complex enough to showcase advance features, but can also be dumbed down, to showcase only basic, and simple functionalities that can be used in a Getting Started Guide for example.

***Goals***
- Build a complex enough application to showcase the full functionality of Kyma ( see proposal #506 and [GoogleCloudPlatform example](https://github.com/GoogleCloudPlatform/microservices-demo) as reference) 
- Split the Application in functional Components ( microservices, micro frontends, serverless functions ) that can be reused and shared across tutorials.
- Discover and surface missing features or improvements that are needed to offer the best Development Experience possible with Kyma.
- Document the development process and the learnings using Blogposts, Youtube videos, Live Coding sessions to expand our social media coverage
- Use new technologies ( focus on buzzwords ) to have a bigger chance of getting viral and create waves in the social network space. Those new technologies ( AI, Machine Learning) can also reveal some of the future proofing necessary for Kyma to be competitive in a broader technology spectrum space.
- Align existing example repositories to the Unified Story
    - https://github.com/kyma-incubator/examples
    - https://github.com/kyma-project/examples
    - https://github.com/SAP-samples/kyma-runtime-extension-samples
    - getting started guide

**Benefits**

By creating one Kyma Showcase Application and having one unified story for our tutorials and demos on all of our platforms  ( kyma-projec.tio, sap.com etc) will help our users to easily follow different tutorials, available on different platforms, and different level of complexity.

**Expected results**

A fully functional Kyma Showcase Application will be available to install. The building components will be available as code and packages so that various variations of the Kyma Showcase App can be assembled depending on the wanted complexity.

We can start with the basic building blocks, for creating a getting started guide, and continue to add new components on the way. The Kyma Showcase Application can be available before theWG ends its activity.

**Expected membership and governance**

* Meeting frequency: weekly
* Membership: 8
* Duration: 6 months

**Previous approach** (optional)

At this moment, every team has it own story when building an example app. The example code and the built components cannot be reused between tutorials and examples.

**Measures of success** 

* The Showcase App follows the recommended architecture for a modern Cloud Native Application
* The Showcase App is complex enough that can showcase all the features that Kyma offers
* The app is composed from individual reusable components written in various programming languages that can be build, deployed  separately

**Assessment frequency**

* Monthly

**Exit criteria**

* Members will be inactive or interest will significantly drop down making it very hard to drive and implement topics
* All the goals will be met/completed
* Global product priorities will change

**Comment by a-thaler** [comment]
Maybe another expected outcome could be to build out a strategy for the examples we have, how to get a unified story there
- https://github.com/kyma-incubator/examples
- https://github.com/kyma-project/examples
- https://github.com/SAP-samples/kyma-runtime-extension-samples
- getting started guide

**Comment by valentinvieriu** [comment]
@a-thaler Good point, I can add all those repos as clear goals to align them to the Story. They are mentioned but not so precise

**Comment by pbochynski** [comment]
Looks good. Approved by me :)

**Comment by a-thaler** [comment]
yep, if we also align the examples I'm fine :)

**Comment by pbochynski** [comment]
W have only approvals, no objections. I hereby declare working group Showcase Application open!
