### ISSUE TITLE
Remove the ASCII header from the chart_README.md template and all chart README.md docs

### ISSUE THREAD

**Issue by kazydek** [kyma-project/community#53]
**Description**

As decided by the SIG Content, the ASCII header needs to be removed from the [`chart_README.md`](https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/chart_README.md) template.
Apart from the template, it must to be removed from all existing chart `README.md` documents in the `kyma` repository.

**Comment by gopikannappan** [comment]
Lukasz G to talk to SiG "Content" and take this forward

**Comment by derberg** [comment]
Actually there are more things that need to be updated in the template. We need to simplify it or think even about removing it.
