### ISSUE TITLE
Describe how to deal with log level change without restart

### ISSUE THREAD

**Issue by dbadura** [kyma-project/community#530]
**Description**
Some components shouldn't be restarted to change log level.
We should unify, or describe what in our opinion is the best approach to change log level.

**Expected result**
Proposal which describe the approach to change log level during runtime
**Actual result**
This [PR](https://github.com/kyma-project/community/pull/525) didn't covered this topic, because it was out of scope in proposal creation:

My first though are:
 - use config map as file and create go runtime which will check the file every 'x' seconds and set appropriate log level.
 - use REST API to set appropriate log level

**Comment by rakesh-garimella** [comment]
I think knative project had the way of reloading the configmap without requirement to restart the controller.  I would recommend to have a look there.
