### ISSUE TITLE
Request a new repository for sample functions

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/community#555]
**Description**

Request a new repository dedicated to lightweight sample functions used in tutorials.
`https://github.com/kyma-project/sample-functions`

**Reasons**

We would like to demonstrate how to deploy functions from git repo source and therefore we need a repo within kyma-org containing sample functions 
Due to the fact that serverless pulls the whole repo and builds selected folder we would like to avoid defining sample functions as new folders in example repo.

**Comment by a-thaler** [comment]
So maybe we should keep the naming a bit aligned, like function-examples? What @kyma-project/technical-writers think about the name? We will need to reference it in the documentation a lot as well.

**Comment by kwiatekus** [comment]
Once we add some sample functions to the repo we will handle the references in the documentation

**Comment by pbochynski** [comment]
What is the impact of reusing examples? I don't think it is big repo. I did the checkout and it took a few seconds and 2.6 MB is the repo size. Did you compare time/memory/whatever with the brand new repository?

**Comment by kwiatekus** [comment]
I haven't check exact size of the repo. I'm glad that you did it @pbochynski. 2.6MB it's not a big transfer so we will add functions to the examples repo to keep it simple and organised. 
Should examples repo grow in the future and its size becomes a problem for our case then we will try to find different solution.
