### ISSUE TITLE
Adjust community docs to the new navigation structure

### ISSUE THREAD

**Issue by kazydek** [kyma-project/community#556]
**Description**

Adjust the structure of docs that are shown on the website to the new structure prepared as part of this [issue](https://github.com/kyma-project/kyma/issues/11029).

Also, these docs should be removed or modified as they will no longer be valid:
- [Add new documentation to the website](https://kyma-project.io/community/guidelines/content#add-new-documentation-to-the-website-add-new-documentation-to-the-website)
- [Links](https://kyma-project.io/community/guidelines/content/#links-links)
- [Document types templates](https://kyma-project.io/community/guidelines/templates/#document-types-templates-document-types-templates)
...same as [Content Strategy](https://kyma-project.io/community/guidelines/content/#content-strategy-content-strategy), [Diagrams](https://kyma-project.io/community/guidelines/content/#diagrams-diagrams), and [Screenshots](https://kyma-project.io/community/guidelines/content/#screenshots-screenshots), but I guess these are already covered by separate issues.

**Area**

Community docs

**Reasons**

Adjusting the docs to the new structure of docs

**Assignees**

@kyma-project/technical-writers

**Attachments**

See the [draft](https://github.com/kazydek/new-docs-structure) of the new structure for reference.

**Comment by klaudiagrz** [comment]
Related issues:
https://github.com/kyma-project/community/issues/543
https://github.com/kyma-project/community/issues/542

**Comment by majakurcius** [comment]
And also: 
#477

**Comment by klaudiagrz** [comment]
Done with one follow-up issue to revisit the content (especially descriptions of processes) in the `community` repo: https://github.com/kyma-project/community/issues/604
