### ISSUE TITLE
Confusing style guide for "for example"

### ISSUE THREAD

**Issue by meeque** [kyma-project/community#60]
**Description**

The [Style and standards](/kyma-project/community/blob/master/guidelines/content-guidelines/style-and-standards.md) guide contains a confusing passage about the terminology of "for example".

**Expected result**

Clarify that "for example" should be used instead of ["e.g."](https://en.wikipedia.org/wiki/List_of_Latin_phrases_(E)#exempli_gratia):

> * "for example", not "e.g."   
> ✅ There are many animals in the zoo. For example: lions, elephants, and zebras.     
> ⛔️ There are many animals in the zoo, for example: lions, elephants, and zebras.  
> ⛔️ There are many animals in the zoo. e.g.: lions, elephants, and zebras.

On the other hand, "for example" should not be used instead of ["i.e."](https://en.wikipedia.org/wiki/List_of_Latin_phrases_(I)#id_est), since that has a different meaning. If you want to cover that, too, this should do:

> * "that is", "that means", "in other words", or "namely", not "i.e."

Sorry, don't have any good examples for that. Should it be used at all?

**Actual result**

The suggested usage of "for example" instead of "i.e." is bad advice, because it would change the meaning of the sentence. In fact, the current example of using "i.e." does not make much sense, unless the only animals that the zoo contains are lions, elephants, and zebras – not sure if that qualifies as "many animals" though.

> * "for example", not "i.e."   
> ✅ There are many animals in the zoo. For example: lions, elephants, and zebras.     
> ⛔️ There are many animals in the zoo, for example: lions, elephants, and zebras.  
> ⛔️ There are many animals in the zoo. i.e.: lions, elephants, and zebras.

**Steps to reproduce**

Read the guide.

**Troubleshooting**

Until this is fixed, one might simply ignore the guide, and just make sure that both "i.e." and "e.g." are expressed in English language.

**Comment by kazydek** [comment]
@meeque, thank you for pointing that out. You are absolutely right and we will update the document accordingly. As for your question regarding the use of `i.e.`, we avoid using contractions and abbreviations in general in the documentation. For issues not defined in our guidelines, we refer to the Microsoft Style Guide. The use of `that is` instead of `i.e.` is described (there)[https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/i/ie].
