### ISSUE TITLE
Shortening time period after which a person is removed/added to CODEOWNERS

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/community#614]
## Context

The [current guidelines](https://github.com/kyma-project/community/blob/main/docs/governance/01-governance.md#when-does-a-maintainer-lose-the-maintainer-status) state that `If a maintainer is unresponsive for at least 3 months, he/she can be removed from the maintainers list immediately.` Moreover, according to the same guidelines, new codeowners can be added to the list after 3 months of working on the project. 

<img width="1046" alt="Screen Shot 2021-12-09 at 15 13 28" src="https://user-images.githubusercontent.com/35192450/145574187-1c8f6720-09f6-42b9-a91c-7c8d5af32bd2.png">

From the [**Process for becoming a codeowner**](https://github.com/kyma-project/community/blob/main/docs/governance/01-governance.md#process-for-becoming-a-codeowner) section:

<img width="1030" alt="Screen Shot 2021-12-10 at 13 29 15" src="https://user-images.githubusercontent.com/35192450/145574292-9153ab95-fa3e-49ca-a990-dc7f0a619834.png">

Because of that, the CODEOWNERS file does not really reflect the reality: it contains names of people no longer working on the project, and people actually working on it do not have codeowners rights. This disrupts the transparency and makes it more difficult to get reviews. 

## Proposal

To make the codeowners list more transparent, I'd suggest:
1. Shortening the time of unresponsiveness after which a person is removed from CODEOWNERS **from 3 months to 1 month**, and/or
2. Shortening the time after which a person is added to CODEOWNERS **from 3 months to 1 month** as well. 
3. Shortening the time period after which a person can be removed from codeowners, but keeping 3 months of probatory period for new joiners.
4. Leave the decision on whether someone should become (or stop being) a codeowner to sole discretion of existing code owners and the person interested in becoming one (as this person should not only be appointed but also willing and feeling comfortable).

**Comment by Disper** [comment]
I’m not sure about whether a good time period exists that will be good for all possible contexts. There might be cases where e.g. 1 month will not be enough for someone to feel comfortable as code owner, while I can image areas where someone can feel comfortable even after one week. 

Tiny additional-proposal
**Four**: Leave decision on whether someone should become a codeowner to sole discretion of existing code owners and the person interested on becoming one (as this person should not only be appointed but also willing and feeling comfortable).

**Comment by pbochynski** [comment]
You are right - the reality is different. We just add new team members to the codeowner files when they are ready. The guide was prepared mostly for external contributors (outside of kyma-project organization). Please check [this proposal](https://github.com/kyma-project/community/issues/613). We can simplify the process for our full-time contributors using area teams. As for now, we don't have any external code-owners (except those who left our team and became emeritus).

**Comment by klaudiagrz** [comment]
Thank you all for your contribution to the discussion 🙇 I implemented changes to the guidelines as suggested.
