### ISSUE TITLE
The link on CONTRIBUTING.md is not working

### ISSUE THREAD

**Issue by mehmetmgrsl** [kyma-project/community#632]
**Description**
The page on https://github.com/kyma-project/community/blob/main/templates/repository-template/CONTRIBUTING.md has the following sentence: 

_"To contribute to this project, follow the rules from the general [**CONTRIBUTING.md**](https://github.com/kyma-project/community/blob/main/contributing/02-contributing.md)[](https://github.com/) document in the community repository."_

In this sentence, "CONTRIBUTING.md"’s link needs to be https://github.com/kyma-project/community/blob/main/docs/contributing/02-contributing.md instead of https://github.com/kyma-project/community/blob/main/contributing/02-contributing.md.

**Area**
area/documentation

**Reasons**

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by klaudiagrz** [comment]
Hi @mehmetmgrsl ! 👋

Thank you for creating the issue. The link is now fixed 🙂

**Comment by mehmetmgrsl** [comment]
> 

You're welcome @klaudiagrz . Thanks for fixing it :)
