### ISSUE TITLE
Decision log template update

### ISSUE THREAD

**Issue by agolawska** [kyma-project/community#64]
Please add an information to the decision log template regarding the possibility to revisit particular decision earlier if needed. In that case a ticket would need to be created.

**Comment by kazydek** [comment]
To clarify: a ticket means the GitHub issue.

**Comment by agolawska** [comment]
Just an additional comment that according to the proposal:

Call to revisit a decision can be raised by SIG/WG members after that date, however Ultimate Decision Makers can request to revisit a decision anytime
