### ISSUE TITLE
Import kyma components / libraries using vanity import path in go

### ISSUE THREAD

**Issue by k15r** [kyma-project/community#644]
## Description
setup go vanity import paths to allow importing kyma related libraries / components using 
`kyma-project.io/<yourcomponent>`. This would allow us to change repositories without having to change imports in the codebase.

## Details
currently all kyma components are imported using `github.com/kyma-project/kyma/...` 
For new components the guidlines state, that those components have to be hosted on `github.com/kyma-incubator/...` until being mature enough to be moved to `github.com/kyma-project`. As a result of this, every component that matured from `kyma-incubator` to `kyma-project` has to be modified, both internally and in every other component that uses this component / library. This could be avoided by leveraging gos vanity import path feature (`go help importpath`). The idea is to import our components using `kyma-project.io/<component>`  and have those import paths be resolved internally to `github.com/kyma-(project|incubator)` or even a different host (not github.com). Movin the codebase from path to path, or even to / from a different repository would then be as easy as migrating the code and have kyma-project.io point to the new location.

As a side effect of this we could even break down the mono repo if that would ever be required.

The move to this solution can be done per component, no need to do it all at once.

A good first component to migrate to this approach could be `kyma-incubator/reconciler` as it needs to be migrated soon.

**Comment by pbochynski** [comment]
I think we go into different direction. We start new modules directly in kyma-project, and we don't need it for now.
