### ISSUE TITLE
Rework style guide for kubernetes resource types

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/community#680]
**Description**
The [style guide](https://kyma-project.io/community/guidelines/content-guidelines/02-style-and-terminology#capitalized-terms) defines a hardcoded list of k8s resource types where a natural language should be used, and not CamelCase.

There is no need to have a hardcoded list as this list will be driven by kubernetes and will change. Anyway, it was never complete, important base types like "DaemonSet" are not covered. So please refer to external docu for a list of applicable types and use some examples only.
Also, we should extend it to CRDs in general, so that we have a convention in place for types like the 3party ones coming from istio "VirtualService" or even our own ones like "APIRule". For me that is all the same problem where we need a consistent appearance in the documentation.

Furthermore, I really have a problem using natural language for these resource types. For me, that are well-defined API elements of the k8s API and with that are "proper nouns/terms" which you should not modify as you will not explicitly reference to that things anymore. You suddenly could mean something else. Talking about a Config Map sounds really strange as it does not strictly relate to the k8s API ConfigMap. I'm fine to even put it in `code` annotations to clearly distinguish between things which you would talk about in natural language. For example an actual deployment of software versus defining a `Deployment`.

Especially in diagrams were you want to outline the different resources and how they reference each other it is strange to use natural language in the boxes of the diagram

Summary: I suggest to use CamelCase for all k8s resource types including any CRD, maybe even annotated with special style.

**Reasons**
Be more precise, we are not talking about an abstract concept but concrete types defined in an API

**Attachments**

**Comment by NHingerl** [comment]
https://github.com/kyma-project/busola/issues/1709
