### ISSUE TITLE
Rename the Kyma/Manifest Operators and Watcher with more meaningful names

### ISSUE THREAD

**Issue by NHingerl** [kyma-project/community#702]
**Description**

Replace the names used for the new operators wherever they are used:

Update: latest status as per https://github.com/kyma-project/community/issues/702#issuecomment-1228133967

- Manifest Operator => Module Manager, `module-manager`
- Kyma Operator => Lifecycle Manager, `lifecycle-manager`
- Kyma Watcher => Runtime Watcher, `runtime-watcher`

In normal text: Capitalized because they're proper names.
In code: Lowercase and with dash `-`.

AC:
- [x] Manifest Operator => Module Manager, `module-manager`
- [x] Kyma Operator => Lifecycle Manager, `lifecycle-manager`
- [x] Kyma Watcher => Runtime Watcher, `runtime-watcher`

**Reasons**

The current names make aren't very descriptive about what each thing does.
Replacing them will improve the intuitive understanding for all stakeholders.

https://github.com/kyma-project/community/issues/700

**Attachments**

**PullRequests**
`kyma-operator` => `lifecycle-manager`:
https://github.com/kyma-project/lifecycle-manager/pull/126
https://github.com/kyma-project/test-infra/pull/5925
https://github.com/kyma-project/module-manager/pull/74
https://github.com/kyma-project/cli/pull/1357
https://github.com/kyma-project/lifecycle-manager/pull/134

`kyma-watcher` => `runtime-watcher`:
https://github.com/kyma-project/runtime-watcher/pull/47
https://github.com/kyma-project/runtime-watcher/pull/48
https://github.com/kyma-project/lifecycle-manager/pull/128
https://github.com/kyma-project/test-infra/pull/5927

`manifest-operator` => `module-manager`:
https://github.com/kyma-project/module-manager/pull/75

**Comment by jakobmoellersap** [comment]
`kyma-operator` => `lifecycle-manager`:
https://github.com/kyma-project/kyma-operator/pull/126
https://github.com/kyma-project/test-infra/pull/5925
https://github.com/kyma-project/manifest-operator/pull/74
https://github.com/kyma-project/cli/pull/1357

**Comment by ruanxin** [comment]
related issue: https://github.com/kyma-project/kyma-operator/issues/127

**Comment by jakobmoellersap** [comment]
`kyma-watcher`=> `runtime-watcher`:
https://github.com/kyma-project/runtime-watcher/pull/47

**Comment by a-thaler** [comment]
When reading "installer" I think of a one-time action which is getting executed in an imperative way. It might be followed by an update. We should use a term which is more neutral or even emphasises the declarative approach. At the end it is also managing the lifecycle (of the module), so maybe we can go with "module-manager", similar to "lifecycle-manager"

**Comment by NHingerl** [comment]
Your point is very valid, but then we've got the problem that it's very similar to the "other" manager - both manage lifecycles, so we need to make clear the difference. "Lifecycle Manager" is now too unspecific, because the "Module Manager" is also a lifecycle manager, just some other thing's lifecycle. So what do we call the "Lifecycle Manager" then? "Kyma Manager" is also bad, because isn't it all related to "Kyma"?

**Comment by jakobmoellersap** [comment]
Please remember that during discussion, we should avoid using `Kyma` anywhere since its already in the Github Org and setting the context.

so it would rather be:
`kyma-project/lifecycle-manager`, `kyma-project/module-manager`, `kyma-project/runtime-listener` right now

**Comment by NHingerl** [comment]
I'm against "Livecycle Manager", because the Module Manager also manages a lifecycle. 
We need something better for the Lifecycle Manager.

**Comment by tobiscr** [comment]
Proposal from the discussion round was:

```
kyma-manager
module-manager
runtime-watcher
```

**Comment by jakobmoellersap** [comment]
Putting to blocked until this is resolved, PRs are too huge to redo this on the fly.

**Comment by adityabhatia** [comment]
I still do not know why we moved away from `operator`. My proposal:
```
kyma-project/lifecycle-operator
kyma-project/module-operator
kyma-project/watcher-operator
```

**Comment by a-thaler** [comment]
```
lifecycle-manager
module-manager
runtime-watcher
```

**Comment by adityabhatia** [comment]
> ```
> lifecycle-manager
> module-manager
> runtime-watcher
> ```

Ok so we stick to these names. I like them.

**Comment by NHingerl** [comment]
@adityabhatia please note that "template operator" also isn't ideal. Isn't this simply a template for modules, aka a "module template"? I suggest renaming it too.

**Comment by jakobmoellersap** [comment]
Template Operator is a temporary working title for our reference implementation / scaffolding project. Longterm its planned to include it into the CLI by default. This will then also remove the `template-operator` name.

**Comment by NHingerl** [comment]
I wasn't involved in that naming :D 
The way it's called now sounds like it is an operator handling templates. Not a reference/template project. 

To avoid further effort, let's keep it as is, but maybe let's discuss the (temporary/permanent) titles right when they come up, then we don't have to rename them so often.
