### ISSUE TITLE
Modify the diagram in the issues-workflow.md document

### ISSUE THREAD

**Issue by kazydek** [kyma-project/community#71]
**Description**

Rewrite the diagram in https://github.com/kyma-project/community/blob/master/issues-workflow.md to match our guidelines: https://github.com/kyma-project/community/blob/master/guidelines/content-guidelines/diagrams.md.
SVG as a source is enough.

**Reasons**

It does not match the guidelines.

**Comment by natasab** [comment]
can you point which guidelines exactly it does not match?

**Comment by kazydek** [comment]
@natasab Here are the guidelines https://github.com/kyma-project/community/blob/master/guidelines/content-guidelines/diagrams.md
