### ISSUE TITLE
Module attributes (beta, internal) independent from release channels

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/community#770]
Created on {2023-04-05} by Piotr Bochynski (@pbochynski).

## Decision log

| Name | Description |
|-----------------------|------------------------------------------------------------------------------------|
| Title | Module attributes (beta, internal) independent from release channels |
| Due date | 2023-04-14 |
| Status | Proposed on 2023-04-05, Accepted on 2023-04-17 |
| Decision type | Choice |
| Affected decisions | None |

## Context

Release channels were introduced to allow users to test new releases of modules before the upgrade is applied automatically in their cluster. During the work on the modularization the release channel concept was reused for introducing beta features (separate channel). Recently the concept was extended again to introduce internal modules (available only for internal teams). At the beginning it was tempting to add more features with the same implementation, but with more aspects to cover the solution was not any more clear and easy to understand. With these 3 aspect the number of channels can grow up to 8 when we would like to cover all combinations (think about fast-beta-internal or similar channels).

It is important to explain what is the meaning of `beta` and `internal`. 
- `beta` is a phase of the development of the module. It means that it is too early to finalise the API, that significant changes are still possible, and even entire module can be discontinued without legal obligations. Once module graduates from beta to production state the customer investment has to be protected with all the constraints about deprecations, changes, etc. Going back from production state to beta is not possible (you can only sunset the module). Introducing experimental features in the existing (production) modules should be realised with feature toggles.
- `internal` modules are not available for external customers regardless of their maturity (beta/production)

## Decision

Stay with just 2 channels: fast and regular with the initial use case (get the stable version or the newest one)
Introduce 2 additional boolean flags on ModuleTemplate (beta, internal) to cover additional use cases.
The default value for both flags would be false. The flags can be added as fields in the spec or as a labels.

## Consequences

- Release strategy and other documents has to be updated (beta release channel -> beta attribute).

**Comment by valentinvieriu** [comment]
I think this approach of separating the internal/external/beta outside of the release channels is easier to understand for the user and will be actually transparent for them.
This will allow the user to opt-in for a beta module as stable or fast

**Comment by a-thaler** [comment]
I like the idea of not mixing the concepts here, so the release channel is really just about the timing on when to get a newer version. However, alpha/beta might fall into the same category as it is about deciding when to get a feature. I like to pick the module and then decide on the channel, so either fast-v1 or stable-v1 or even beta-v2.
Summarized, is the beta idea really not falling into the channel concept?

The labels/attributes should focus on metadata, not versions. Like "internal" or "for-free"

**Comment by varbanv** [comment]
I am all for simplifying as much as possible. So :+1:

**Comment by a-thaler** [comment]
We discussed once more and I think it is fine to have beta as meta-attribute as well, if we clearly exclude the use case of having a betav2 ready in parallel to a stablev1. Indeed that use case is not required as the major versions should be modelled via the CRD versions, so major changes should be made available via the new CRD versions where even alpha/beta is usable.

Another discussion is if we want to use simple tags like "internal", "beta" or real labels with key/values like "audience=internal". I vote for key/values as it will make it more transparent on which keys a release decision might be influenced. Also I vote for not having keys like "internal=true" but instead use something like "audience=internal". If we need to introduce later other values which are excluding each other "audience=partner" that is more intuitive to use and validation is out of the box.

**Comment by ruanxin** [comment]
I have some doubts regarding this new beta flag. Typically, the term 'beta' is commonly used in release channels. Why this flag is being designed separately from those channels, maybe it will confuse module designers and end users.

About the internal flag, just want to get some clarification regarding the usage, if the module template is configured as internal, does it means that module template should never be available to SKR on the managed mode?

**Comment by pbochynski** [comment]
> I have some doubts regarding this new beta flag. Typically, the term 'beta' is commonly used in release channels. Why this flag is being designed separately from those channels, maybe it will confuse module designers and end users.
> 
I started from the same point of view. But you can still have beta several versions of beta module, and beta users also could benefit from having control over the module update schedule. Having separate attribute enables that feature (without introducing beta-fast, beta-regular channels).

> About the internal flag, just want to get some clarification regarding the usage, if the module template is configured as internal, does it means that module template should never be available to SKR on the managed mode?

Internal means that it is distributed only to the users from our company (not external customers). Our internal users still want managed offering.

**Comment by pbochynski** [comment]
> Another discussion is if we want to use simple tags like "internal", "beta" or real labels with key/values like "audience=internal". I vote for key/values as it will make it more transparent on which keys a release decision might be influenced. Also I vote for not having keys like "internal=true" but instead use something like "audience=internal". If we need to introduce later other values which are excluding each other "audience=partner" that is more intuitive to use and validation is out of the box.

I am not sure if it is actually better. What if partner some module should be available to partners and to internal teams, and other module only to partners? I do not know if we would have other values for audience in the future so I would rather start with boolean.

**Comment by marco-porru** [comment]
Since beta is not designed to host innovative features on existing modules, I vote it too for it.

But I have a question: As defined in the [Release Channels](https://github.com/kyma-project/community/tree/main/concepts/modularization#release-channels) the Beta was without SLA. will it have SLA as a beta module instead, since part of fast or regular?

**Comment by pbochynski** [comment]
I added some explanations based on Marco's questions:

It is important to explain what is the meaning of `beta` and `internal`. 
- `beta` is a phase of the development of the module. It means that it is too early to finalise the API, that significant changes are still possible, and even entire module can be discontinued without legal obligations. Once module graduates from beta to production state the customer investment has to be protected with all the constraints about deprecations, changes, etc. Going back from production state to beta is not possible (you can only sunset the module). Introducing experimental features in the existing (production) modules should be realised with feature toggles.
- `internal` modules are not available for external customers regardless of their maturity (beta/production)

**Comment by pbochynski** [comment]
> Since beta is not designed to host innovative features on existing modules, I vote too for it.
> 
> But I have a question: As defined in the [Release Channels](https://github.com/kyma-project/community/tree/main/concepts/modularization#release-channels) the Beta was without SLA. will it have SLA as a beta module instead, since part of fast or regular?

SLA is part of managed offering and is covered in the internal decision record.

**Comment by pbochynski** [comment]
Decision accepted and implemented.
