### ISSUE TITLE
Make Release Channels content an internal configuration of managed offering

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/community#775]
Created on 2023-04-13 by Piotr Bochynski (@pbochynski).

## Decision log

| Name | Description |
|-----------------------|------------------------------------------------------------------------------------|
| Title | Make Release Channels content an internal configuration of managed offering |
| Due date | 2023-04-18 |
| Status | Proposed on 2023-04-13, Accepted on 2023-04-18 |
| Decision type | Binary |
| Affected decisions | None |

## Context

Kyma introduced release channels as part of its modularization strategy, with two main channels - fast and regular. Each Kyma module publishes a ModuleTemplate that is a descriptor of the module version (release). The ModuleTemplate can be assigned to a release channel, which is just a string field in the ModuleTemplate. When using Kyma as a service, customers receive a list of module templates that are replicated from Kyma Control Plane (KCP) and can pick and enable the modules they are interested in. The Kyma Lifecycle Manager (KLM) operator then installs the proper module manager (operator) in the cluster. Release channels are useful in the managed offering as users can choose between fast and regular channels, ensuring they always have access to the latest modules and updates without needing to upgrade manually.

While release channels are helpful in a managed offering, in most cases in the open source case, it is easier to install the module operator in the desired version and skip the entire release channel concept. Therefore, maintaining release channels in the public open source repository would not provide significant value to the community. Instead, users of the open-source version can choose which module version goes into which release channel, or skip release channels altogether. It is SAP's responsibility to assign modules to the channels and ensure proper stability and security in the managed offering.

## Decision

The release channels content will become an internal configuration of the managed offering (Kyma as a service). In the open source release channels **will not** be maintained.

## Consequences

- The release channels feature will not be maintained in the public open source repository, and users will need to manage their own release channels if they choose to use them.
- Users of the managed offering will have access to release channels and can choose between fast and regular channels for their modules.
- Users of the open-source version can still use module templates and choose which module version to use, but will need to manage their own release channels. 
- Open source modules should have module templates published as release artefacts. Kyma CLI will get a command to install module templates from latest releases. The command will use the hard coded configuration to fetch templates from github (e.g. Keda will point to https://github.com/kyma-project/keda-manager/releases/latest/download/moduletemplate.yaml). 
- Users who have access to the internal configuration of managed offering would be able to use it also in their own (not managed) clusters. 
- The release channels as a feature should be described in the Lifecycle Manager documentation (is it a property of ModuleTemplate and Kyma resource). The feature should be described in the generic way without reference to channel names used in managed offering (fast/regular)

**Comment by pbochynski** [comment]
Based on feedback I added 2 points:
- Open source modules should have module templates published as release artefacts. Kyma CLI will get a command to install module templates from latest releases. The command will use the hard coded configuration to fetch templates from github (e.g. Keda will point to https://github.com/kyma-project/keda-manager/releases/latest/download/moduletemplate.yaml).
- Users who have access to the internal configuration of managed offering would be able to use it also in their own (not managed) clusters.

**Comment by arturskorupa** [comment]
@pbochynski are 3rd party module templates also going to published along with Kyma modules, or they should be published in the origin repository, where the code is stored.

**Comment by arturskorupa** [comment]
@pbochynski is there any process (module submission, module release) that's will output module templates to the latest folder?

**Comment by pbochynski** [comment]
Decision accepted and implemented.
