### ISSUE TITLE
Store the support link in ModuleTemplate

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/community#789]
Created on 2023-05-19 by Jan Medrek @janmedrek.

## Decision log

| Name | Description |
|-----------------------|------------------------------------------------------------------------------------|
| Title | Store the support link in ModuleTemplate |
| Due date | 2023-05-26 |
| Status | Accepted on 2023-05-26 |
| Decision type | Binary |
| Affected decisions | None |

## Context

In order to simplify the support process and direct the user to the proper support page for a specific module it would be great to provide them with some reference. This can be stored in the ModuleTemplate CR for easy access.

The link can lead to the support page, [communication channel](https://kyma-community.slack.com/archives/CBLBESMST) or the [GitHub issue creation page](https://github.com/kyma-project/keda-manager/issues/new?assignees=&labels=&projects=&template=bug-report.md).

## Decision

The decision is to keep the support link in the ModuleTemplate by using the `operator.kyma-project.io/support-url` annotation.

## Consequences

Keeping the support link in the ModuleTemplate makes it easier for users to find help regarding the module when needed. It can be displayed in the UI for easy access. Using the link is also a generic way of handling the problem, which will provide an option for modules to direct to the proper place regardless of what system is being used to handle support procedures.

**Comment by arturskorupa** [comment]
Along with support link we should also be able to provide additional parameters (filled in the placeholders provided by the link). That could let us already prefill a form for requesting support with all desired data (e.g. coordinates of cluster).

It means we should sync to the Kyma CR in the runtime more details about cluster (GA id, SA id) to simplify the troubleshooting. As far as I know It's currently available in KLM.

**Comment by janmedrek** [comment]
@arturskorupa, please have a look at this issue: https://github.com/kyma-project/community/issues/790#issue-1716956953. There is an option to provide additional labels/annotations for the ModuleTemplate.

On the other hand, I am not sure we should put so much platform-related stuff into the ModuleTemplates/Kyma CR, perhaps it would make more sense to store it somewhere else in the cluster, would need more discussion and planning for that case.

**Comment by lautoma** [comment]
The idea to provide a support URL is great, but let's remember that we one entry point for external customers (https://launchpad.support.sap.com) and internal (https://support.wdf.sap.corp), so displaying the right one directly in the module seems impossible to me. The best solution would be to build a "smart" entry point accessible to both internal and external customers, that would display the correct URL based on GA/SA.
