### ISSUE TITLE
New installation procedure for open source Kyma

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/community#792]
Created on 2023-06-02 by Piotr Bochynski (@pbochynski)

## Decision log

| Name | Description |
|-----------------------|------------------------------------------------------------------------------------|
| Title | Direct module installation |
| Due date | 2023-06-09 |
| Status | Proposed on 2023-06-02, Accepted on 2023-06-09 |
| Decision type | Binary |
| Affected decisions |  - |

## Context

As release channels are moved to the internal repository of managed Kyma the responsibility to set up channels content (pick the suitable module versions) is now on the user's side. But most open source users will be overwhelmed with the additional complexity of setting up the Kyma control plane with the lifecycle-manager and managing their own release channel content. The value of control-plane is visible only if you have to manage a significant number of Kyma clusters that can have different set of modules and different configurations (like manage Kyma Runtime use case). For users that just want to use a few Kyma modules in their cluster, it can be overkill (even if Kyma CLI offers a way to set up Kyma control plane components). It can be explained better with a real example. Let's compare the installation and upgrade of Serverless module with and without using Kyma control plane.

| Installation with control plane | Installation without control plane |
| ---|---|
|1. Install lifecycle-manager in your control plane cluster (it can be installed in the same cluster but you need to grant cluster-admin to lifecycle-manager service account) <br> 2. Create module template for the selected version of serverless module (you can use module template published as a [release artifact in the serverless-manager repository](https://github.com/kyma-project/serverless-manager/releases)) <br> 3. Apply module template in the control-plane (adjust release channel properly) <br> 4. Create Kyma resource that represents the target cluster and the secret with kubeconfig for that cluster (in the single cluster mode kubeconfig is not required) <br> 5. Add serverless module to the spec.modules section of Kyma resource (can be also done with kyma CLI or Kyma Dashboard) <br> 6. Edit default serverless resource to modify the configuration. | 1. Deploy serverless-manager <br> 2. Apply module configuration |

You can clearly see that the control-plane way is much harder and it makes sense only if you use managed solution. In the managed solution steps 1-4 are executed by the Kyma team and the end-user can just enable the module with one command/click (step number 6 is optional as the default configuration in most cases works fine)

The two steps to enable module without control plane are simple kubectl commands:
```sh
kubectl apply -f https://github.com/kyma-project/serverless-manager/releases/latest/download/serverless-manager.yaml
kubectl apply -f https://github.com/kyma-project/serverless-manager/releases/latest/download/serverless-default-cr.yaml
```

To upgrade serverless component to the new latest version all the user has to do is execute again installation step:
```
kubectl apply -f https://github.com/kyma-project/serverless-manager/releases/latest/download/serverless-manager.yaml
```
__Note: of course on production system you should use specific versions instead of latest to ensure reproducible deployments__

## Decision

Use kubectl command to deploy module operators (managers) and their configuration as a standard way of installing Kyma modules. 

## Consequences

- each module should publish kubernetes manifest to deploy operator and sample/default custom resource to create and configure  module instance
- main kyma website should contain index of open source modules with the commands to install module (2 kubectl apply commands)
- `kyma deploy` command is going to be depracated when the last component is moved to the module. Alternatively kyma CLI can support module installation by maintaining list of modules and links to their operator manifests (latest / specific version if provided by user)
- module template is not a mandatory release artifact (it can be created on the fly when the module version is submitted to the release channel in the managed offering)

**Comment by ptesny** [comment]
How will it impact `kyma-deploy` cli?

**Comment by varbanv** [comment]
I would like to avoid the complexity of the control plane install for simple scenarios.
However, given that we do have some OS users that can benefit from the control plane and we should have an "installer" for the control plane, could we take a middle ground approach where `kyma deploy` can be used to deploy the control plane and any number of components as part of an index page the the CLI reads? Then the index can contain the necessary additional links to the required manifests. 
So a user could do:
`kyma deploy cp [version]` to deploy the control plane
`kyma deploy serverless [version]` to deploy serverless
etc.

**Comment by pbochynski** [comment]
> I would like to avoid the complexity of the control plane install for simple scenarios.
> However, given that we do have some OS users that can benefit from the control plane and we should have an "installer" for the control plane, could we take a middle ground approach where `kyma deploy` can be used to deploy the control plane and any number of components as part of an index page the the CLI reads? Then the index can contain the necessary additional links to the required manifests.
> So a user could do:
> `kyma deploy cp [version]` to deploy the control plane
> `kyma deploy serverless [version]` to deploy serverless
> etc.

What is the action behind `kyma deploy serverless`? If it just installs the serverless operator the previous command is not needed (kyma deploy cp). The main scenario for the control plane requires separate clusters (one for the control plane and many for runtimes). Having a sequence like `deploy cp; deploy serverless` should never happen in real life as it implies installing a serverless operator in the control plane. If `kyma deploy serverless` just enables the module in the Kyma CR it is the same as the existing command `kyma enable module serverless`.

I think we should be careful in mixing the installation of the control plane and the installation of kyma modules in the single command. These are completely different stories. We didn't provide any CLI support for people running their own Kyma Control Plane in the past. To be honest I don't think there is anybody else that runs Kyma Control Plane on its own apart from the managed Kyma in SAP BTP. Additionally setting up a control plane with the command we have now (`kyma alpha deploy`) should never be used on production. It is used just for testing lifecycle-manager without a need to create additional clusters for runtimes. Without all other functionalities like provisioning runtime clusters, managing their kubeconfigs, and creating central Kyma resources, it makes a false assumption that managing a control plane is as easy as one CLI command.

**Comment by pbochynski** [comment]
> How will it impact `kyma deploy` cli?
> 
> I like the ease of use and simplicity of it. Can we preserve it?

I think we can keep that shortcut to install all the modules with a default configuration in the kyma CLI. Maybe you missed it:
_Alternatively kyma CLI can support module installation by maintaining list of modules and links to their operator manifests (latest / specific version if provided by user)_
However, we can't support specific kyma versions (as we do not have kyma versions anymore), but just individual module versions. If you want to install multiple modules at once with single command only the latest version makes sense. 

So we could have something like:
- `kyma deploy -m serverless` translated to:
```
kubectl apply -f https://github.com/kyma-project/serverless-manager/releases/latest/download/serverless-manager.yaml
kubectl apply -f https://github.com/kyma-project/serverless-manager/releases/latest/download/serverless-default-cr.yaml
```
- `kyma deploy -m keda` translated to:
```
kubectl apply -f https://github.com/kyma-project/keda-manager/releases/latest/download/keda-manager.yaml
kubectl apply -f https://github.com/kyma-project/keda-manager/releases/latest/download/keda-default-cr.yaml
```
- `kyma deploy -m all` that combines all modules in one command

Please bear in mind that if the operators provide single manifests as release artifacts such a command does not help too much, because most of people would rather install individual modules instead of all. Let me show you the difference on the example where user wants only istio, telemetry and serverless. 

## Installation with the default configuration

**Kyma CLI version**
```
curl -Lo kyma https://storage.googleapis.com/kyma-cli-unstable/kyma-darwin # kyma-linux or kyma.exe
chmod +x kyma
mv ./kyma /usr/local/bin/kyma

kyma deploy -m istio -m telemetry -m serverless
```

**kubectl version**
```
kubectl apply -f https://github.com/kyma-project/istio/releases/latest/download/istio-manager.yaml
kubectl apply -f https://github.com/kyma-project/istio/releases/latest/download/istio-default-cr.yaml
kubectl apply -f https://github.com/kyma-project/telemetry-manager/releases/latest/download/telemetry-manager.yaml
kubectl apply -f https://github.com/kyma-project/telemetry-manager/releases/latest/download/telemetry-default-cr.yaml
kubectl apply -f https://github.com/kyma-project/serverless-manager/releases/latest/download/serverless-manager.yaml
kubectl apply -f https://github.com/kyma-project/serverless-manager/releases/latest/download/serverless-default-cr.yaml
```

## Installation with custom config and version
**Kyma CLI version**
```
curl -Lo kyma https://storage.googleapis.com/kyma-cli-unstable/kyma-darwin # kyma-linux or kyma.exe
chmod +x kyma
mv ./kyma /usr/local/bin/kyma

kyma deploy -m istio -cr my-istio.yaml -v 1.16.1
kyma deploy -m telemetry -cr my-telemetry.yaml -v 1.0.2
kyma deploy -m serverless -cr my-serverless.yaml -v 2.12.2

```

**kubectl version**
```
kubectl apply -f https://github.com/kyma-project/istio/releases/download/1.16.1/istio-manager.yaml
kubectl apply -f my-istio.yaml
kubectl apply -f https://github.com/kyma-project/telemetry-manager/releases/download/1.0.2/telemetry-manager.yaml
kubectl apply -f my-telemetry.yaml
kubectl apply -f https://github.com/kyma-project/serverless-manager/releases/download/2.12.2/serverless-manager.yaml
kubectl apply -f my-serverless.yaml
```

As you see there is not a big difference between kyma CLI and direct kubectl commands. Both are quite simple.

**Comment by ptesny** [comment]
> Note: the commands I used do not exist - treat it as proposal
Thanks; I like the proposal; I still think that having a dedicated deployment command will make a difference (even if as of today the overhead of the raw kubectl commands sequence is allegedly not that big)

**Comment by grego952** [comment]
Shouldn't each module adopt these instructions and keep them in its own repo?
We can have a landing page that will mention all the modules and link to the instructions from there.
For example, please take a look at the Keda module and its different [installation options](https://github.com/kyma-project/keda-manager/blob/004d7fdd1f975f373c4f16657ec87c1d9c5f6f33/docs/contributor/01-01-installation.md).

**Comment by pbochynski** [comment]
We need a link to the module anyway. But we can have also the copy&paste friendly snippet with two `kubectl apply` commands on the main page. For more configuration options you will follow the link, but if you just want to install the module quickly we can have a duplicate on the main page. Pointing to the latest release will make the instruction stable (no need to update it with a new module version).
But I would also unify the module documentation: the installation with lifecycle-manager should be removed completely or moved somewhere deep into the contribution guide.

**Comment by grego952** [comment]
>. But I would also unify the module documentation: the installation with lifecycle-manager should be removed completely or moved somewhere deep into the contribution guide.

Does it mean that the [Enable and Disable](https://github.com/kyma-project/kyma/pull/17579) tutorial should be also removed/hidden deeper?

**Comment by pbochynski** [comment]
> Does it mean that the https://github.com/kyma-project/kyma/pull/17579 tutorial should be also removed/hidden deeper?

Open-source users will not have Kyma resources in their clusters. This is relevant only for managed Kyma runtime or for people running their own control plane (if there are any). 
So yes - it should be removed from the open source and replaced by the list of modules with 2 line instructions on how to enable them.

**Comment by pbochynski** [comment]
Decision accepted.
