### ISSUE TITLE
Search feature in kyma-project.io misses results

### ISSUE THREAD

**Issue by marco-porru** [kyma-project/community#908]
**Description**

The search feature in the kyma-project.io website is not providing the expected results.
It looks it's searching only across "locally" indexed content.

**Expected result**

"Set Up a Custom Domain for a Workload" page and others are shown.

**Actual result**

"Set Up a Custom Domain for a Workload" is not part of the search result, and the list is pretty empty.

**Steps to reproduce**

1. Open the home page kyma-project.io 
2. Navigate to the "Set Up a Custom Domain for a Workload" page
3. Go back to the home page
4. Search for "domain" like in the below image
  <img width="1904" alt="Screenshot 2024-03-21 at 10 15 35" src="https://github.com/kyma-project/community/assets/57440567/5e60bf07-187b-4a1b-97c3-7f4aa6eb8af5">

6. Check the "Set Up a Custom Domain for a Workload" page is shown in the results
7. Open incognito mode in the browser
8.  Open the home page kyma-project.io (DON'T NAVIGATE TO ANY ADDITIONAL SUB PAGE)
9. Search for "domain" like in the below image
<img width="1904" alt="Screenshot 2024-03-21 at 10 16 03" src="https://github.com/kyma-project/community/assets/57440567/0578a455-a838-424f-b990-4c78d3713624">

**Troubleshooting**

Nothing

**Comment by mmitoraj** [comment]
@pbochynski proposed a solution. TBC
